import { ITEM_CATALOG, ITEM_QUALITIES, ITEM_TYPES } from "../../data/itemCatalog";

export const FRONT_ITEM_TYPES = ITEM_TYPES;
export const FRONT_ITEM_QUALITIES = ITEM_QUALITIES;
export const FRONT_ITEM_CATALOG = ITEM_CATALOG;

export const FRONT_ROLES = [
  { id: "r1", name: "刘一", avatar: "刘", skill: "按轮次揭示黄→圣级物品的品质。" },
  { id: "r2", name: "陈二", avatar: "陈", skill: "按轮次揭示黄→圣级物品的轮廓。" },
  { id: "r3", name: "张三", avatar: "张", skill: "每轮在未知品质中各揭示一件最高/最低品质物品的品质。" },
  { id: "r4", name: "李四", avatar: "李", skill: "每轮在未知信息中各揭示一件最高/最低品质物品的轮廓。" },
  { id: "r5", name: "王五", avatar: "王", skill: "按类型分轮揭示对应最高品质物品的品质。" },
  { id: "r6", name: "赵六", avatar: "赵", skill: "按类型分轮揭示对应物品的全部轮廓。" },
  { id: "r7", name: "孙七", avatar: "孙", skill: "按圣→黄顺序揭示对应品质物品的平均格数。" },
  { id: "r8", name: "周八", avatar: "周", skill: "按圣→黄顺序揭示对应品质物品的总格数。" },
  { id: "r9", name: "吴九", avatar: "吴", skill: "按轮次揭示不同品质组合的物品数量。" },
  { id: "r10", name: "郑十", avatar: "郑", skill: "按轮次揭示不同品质组合的物品均价。" },
  { id: "r11", name: "炼丹师", avatar: "丹", skill: "按轮次揭示丹药的数量、总格数、轮廓、品质与全部物品。" },
  { id: "r12", name: "炼器师", avatar: "器", skill: "按轮次揭示武器的数量、总格数、轮廓、品质与全部物品。" },
  { id: "r13", name: "阵法师", avatar: "阵", skill: "按轮次揭示阵法的数量、总格数、轮廓、品质与全部物品。" },
  { id: "r14", name: "符箓师", avatar: "符", skill: "按轮次揭示符箓的数量、总格数、轮廓、品质与全部物品。" },
  { id: "r15", name: "灵植师", avatar: "植", skill: "按轮次揭示灵植的数量、总格数、轮廓、品质与全部物品。" },
  { id: "r16", name: "灵兽师", avatar: "兽", skill: "按轮次揭示灵兽的数量、总格数、轮廓、品质与全部物品。" },
] as const;

const HEXAGRAM_SHORT_BY_NAME: Record<string, string> = {
  坤为地: "坤", 山地剥: "剥", 水地比: "比", 风地观: "观", 雷地豫: "豫", 火地晋: "晋", 泽地萃: "萃", 天地否: "否",
  地山谦: "谦", 艮为山: "艮", 水山蹇: "蹇", 风山渐: "渐", 雷山小过: "小过", 火山旅: "旅", 泽山咸: "咸", 天山遁: "遁",
  地水师: "师", 山水蒙: "蒙", 坎为水: "坎", 风水涣: "涣", 雷水解: "解", 火水未济: "未济", 泽水困: "困", 天水讼: "讼",
  地风升: "升", 山风蛊: "蛊", 水风井: "井", 巽为风: "巽", 雷风恒: "恒", 火风鼎: "鼎", 泽风大过: "大过", 天风姤: "姤",
  地雷复: "复", 山雷颐: "颐", 水雷屯: "屯", 风雷益: "益", 震为雷: "震", 火雷噬嗑: "噬嗑", 泽雷随: "随", 天雷无妄: "无妄",
  地火明夷: "明夷", 山火贲: "贲", 水火既济: "既济", 风火家人: "家人", 雷火丰: "丰", 离为火: "离", 泽火革: "革", 天火同人: "同人",
  地泽临: "临", 山泽损: "损", 水泽节: "节", 风泽中孚: "中孚", 雷泽归妹: "归妹", 火泽睽: "睽", 兑为泽: "兑", 天泽履: "履",
  地天泰: "泰", 山天大畜: "大畜", 水天需: "需", 风天小畜: "小畜", 雷天大壮: "大壮", 火天大有: "大有", 泽天夬: "夬", 乾为天: "乾",
};

function createTool(id: string, name: string, cost: number, desc: string, effect: any) {
  return { id, name, short: HEXAGRAM_SHORT_BY_NAME[name] || name[0], cost, desc, effect };
}

export const FRONT_TOOLS = [
  createTool("t01", "乾为天", 1000, "随机显示2个物品", { type: "revealItem", scope: { kind: "random", count: 2 } }),
  createTool("t02", "天地否", 2000, "随机显示4个物品", { type: "revealItem", scope: { kind: "random", count: 4 } }),
  createTool("t03", "天雷无妄", 5000, "随机显示6个物品", { type: "revealItem", scope: { kind: "random", count: 6 } }),
  createTool("t04", "天山遁", 10000, "随机显示8个物品", { type: "revealItem", scope: { kind: "random", count: 8 } }),
  createTool("t05", "天火同人", 20000, "随机显示10个物品", { type: "revealItem", scope: { kind: "random", count: 10 } }),
  createTool("t06", "天水讼", 100000, "显示所有物品", { type: "revealItem", scope: { kind: "all" } }),
  createTool("t07", "天泽履", 5000, "随机显示最大格子数中的1个物品", { type: "revealItem", scope: { kind: "maxSizeOne" } }),
  createTool("t08", "天风姤", 8000, "随机显示最高品质中的1个物品", { type: "revealItem", scope: { kind: "highestQualityOne" } }),
  createTool("t09", "地天泰", 80000, "显示所有圣级物品的总价", { type: "summary", metric: "totalPrice", scope: { kind: "quality", qualities: ["圣"] } }),
  createTool("t10", "坤为地", 40000, "显示所有天级物品的总价", { type: "summary", metric: "totalPrice", scope: { kind: "quality", qualities: ["天"] } }),
  createTool("t11", "地雷复", 10000, "显示所有地级物品的总价", { type: "summary", metric: "totalPrice", scope: { kind: "quality", qualities: ["地"] } }),
  createTool("t12", "地山谦", 5000, "显示所有玄级物品的总价", { type: "summary", metric: "totalPrice", scope: { kind: "quality", qualities: ["玄"] } }),
  createTool("t13", "地火明夷", 2000, "显示所有黄级物品的总价", { type: "summary", metric: "totalPrice", scope: { kind: "quality", qualities: ["黄"] } }),
  createTool("t14", "地水师", 100000, "显示所有物品的总价", { type: "summary", metric: "totalPrice", scope: { kind: "all" } }),
  createTool("t15", "地泽临", 5000, "显示最大格子数的物品总价", { type: "summary", metric: "totalPrice", scope: { kind: "maxSizeAll" } }),
  createTool("t16", "地风升", 20000, "显示最高品质的物品总价", { type: "summary", metric: "totalPrice", scope: { kind: "highestQualityAll" } }),
  createTool("t17", "雷天大壮", 500, "随机显示2个物品的品质", { type: "revealQuality", scope: { kind: "random", count: 2 } }),
  createTool("t18", "雷地豫", 1000, "随机显示4个物品的品质", { type: "revealQuality", scope: { kind: "random", count: 4 } }),
  createTool("t19", "震为雷", 2000, "随机显示6个物品的品质", { type: "revealQuality", scope: { kind: "random", count: 6 } }),
  createTool("t20", "雷山小过", 5000, "随机显示8个物品的品质", { type: "revealQuality", scope: { kind: "random", count: 8 } }),
  createTool("t21", "雷火丰", 10000, "随机显示10个物品的品质", { type: "revealQuality", scope: { kind: "random", count: 10 } }),
  createTool("t22", "雷水解", 60000, "显示所有物品的品质", { type: "revealQuality", scope: { kind: "all" } }),
  createTool("t23", "雷泽归妹", 800, "随机显示最大格子数中的1个物品的品质", { type: "revealQuality", scope: { kind: "maxSizeOne" } }),
  createTool("t24", "雷风恒", 2000, "随机显示最高品质中的1个物品的品质", { type: "revealQuality", scope: { kind: "highestQualityOne" } }),
  createTool("t25", "山天大畜", 500, "随机显示2个物品的轮廓", { type: "revealContour", scope: { kind: "random", count: 2 } }),
  createTool("t26", "山地剥", 800, "随机显示4个物品的轮廓", { type: "revealContour", scope: { kind: "random", count: 4 } }),
  createTool("t27", "山雷颐", 1500, "随机显示6个物品的轮廓", { type: "revealContour", scope: { kind: "random", count: 6 } }),
  createTool("t28", "艮为山", 4000, "随机显示8个物品的轮廓", { type: "revealContour", scope: { kind: "random", count: 8 } }),
  createTool("t29", "山火贲", 8000, "随机显示10个物品的轮廓", { type: "revealContour", scope: { kind: "random", count: 10 } }),
  createTool("t30", "山水蒙", 30000, "显示所有物品的轮廓", { type: "revealContour", scope: { kind: "all" } }),
  createTool("t31", "山泽损", 800, "随机显示最大格子数中的1个物品的轮廓", { type: "revealContour", scope: { kind: "maxSizeOne" } }),
  createTool("t32", "山风蛊", 2000, "随机显示最高品质中的1个物品的轮廓", { type: "revealContour", scope: { kind: "highestQualityOne" } }),
  createTool("t33", "火天大有", 50000, "显示所有圣级物品的数量", { type: "summary", metric: "count", scope: { kind: "quality", qualities: ["圣"] } }),
  createTool("t34", "火地晋", 10000, "显示所有天级物品的数量", { type: "summary", metric: "count", scope: { kind: "quality", qualities: ["天"] } }),
  createTool("t35", "火雷噬嗑", 5000, "显示所有地级物品的数量", { type: "summary", metric: "count", scope: { kind: "quality", qualities: ["地"] } }),
  createTool("t36", "火山旅", 2000, "显示所有玄级物品的数量", { type: "summary", metric: "count", scope: { kind: "quality", qualities: ["玄"] } }),
  createTool("t37", "离为火", 1000, "显示所有黄级物品的数量", { type: "summary", metric: "count", scope: { kind: "quality", qualities: ["黄"] } }),
  createTool("t38", "火水未济", 5000, "显示所有物品的数量", { type: "summary", metric: "count", scope: { kind: "all" } }),
  createTool("t39", "火泽睽", 500, "显示最大格子数的物品数量", { type: "summary", metric: "count", scope: { kind: "maxSizeAll" } }),
  createTool("t40", "火风鼎", 5000, "显示最高品质的物品数量", { type: "summary", metric: "count", scope: { kind: "highestQualityAll" } }),
  createTool("t41", "水天需", 20000, "显示所有圣级物品的均价", { type: "summary", metric: "avgPrice", scope: { kind: "quality", qualities: ["圣"] } }),
  createTool("t42", "水地比", 8000, "显示所有天级物品的均价", { type: "summary", metric: "avgPrice", scope: { kind: "quality", qualities: ["天"] } }),
  createTool("t43", "水雷屯", 4000, "显示所有地级物品的均价", { type: "summary", metric: "avgPrice", scope: { kind: "quality", qualities: ["地"] } }),
  createTool("t44", "水山蹇", 1000, "显示所有玄级物品的均价", { type: "summary", metric: "avgPrice", scope: { kind: "quality", qualities: ["玄"] } }),
  createTool("t45", "水火既济", 500, "显示所有黄级物品的均价", { type: "summary", metric: "avgPrice", scope: { kind: "quality", qualities: ["黄"] } }),
  createTool("t46", "坎为水", 20000, "显示所有物品的均价", { type: "summary", metric: "avgPrice", scope: { kind: "all" } }),
  createTool("t47", "水泽节", 500, "显示最大格子数的物品均价", { type: "summary", metric: "avgPrice", scope: { kind: "maxSizeAll" } }),
  createTool("t48", "水风井", 5000, "显示最高品质的物品均价", { type: "summary", metric: "avgPrice", scope: { kind: "highestQualityAll" } }),
  createTool("t49", "泽天夬", 40000, "显示所有圣级物品的总格数", { type: "summary", metric: "totalSize", scope: { kind: "quality", qualities: ["圣"] } }),
  createTool("t50", "泽地萃", 8000, "显示所有天级物品的总格数", { type: "summary", metric: "totalSize", scope: { kind: "quality", qualities: ["天"] } }),
  createTool("t51", "泽雷随", 4000, "显示所有地级物品的总格数", { type: "summary", metric: "totalSize", scope: { kind: "quality", qualities: ["地"] } }),
  createTool("t52", "泽山咸", 1000, "显示所有玄级物品的总格数", { type: "summary", metric: "totalSize", scope: { kind: "quality", qualities: ["玄"] } }),
  createTool("t53", "泽火革", 500, "显示所有黄级物品的总格数", { type: "summary", metric: "totalSize", scope: { kind: "quality", qualities: ["黄"] } }),
  createTool("t54", "泽水困", 2000, "显示所有物品的总格数", { type: "summary", metric: "totalSize", scope: { kind: "all" } }),
  createTool("t55", "兑为泽", 500, "显示最大格子数的物品总格数", { type: "summary", metric: "totalSize", scope: { kind: "maxSizeAll" } }),
  createTool("t56", "泽风大过", 2000, "显示最高品质的物品总格数", { type: "summary", metric: "totalSize", scope: { kind: "highestQualityAll" } }),
  createTool("t57", "风天小畜", 10000, "显示所有圣级物品的平均格数", { type: "summary", metric: "avgSize", scope: { kind: "quality", qualities: ["圣"] } }),
  createTool("t58", "风地观", 5000, "显示所有天级物品的平均格数", { type: "summary", metric: "avgSize", scope: { kind: "quality", qualities: ["天"] } }),
  createTool("t59", "风雷益", 1000, "显示所有地级物品的平均格数", { type: "summary", metric: "avgSize", scope: { kind: "quality", qualities: ["地"] } }),
  createTool("t60", "风山渐", 500, "显示所有玄级物品的平均格数", { type: "summary", metric: "avgSize", scope: { kind: "quality", qualities: ["玄"] } }),
  createTool("t61", "风火家人", 500, "显示所有黄级物品的平均格数", { type: "summary", metric: "avgSize", scope: { kind: "quality", qualities: ["黄"] } }),
  createTool("t62", "风水涣", 500, "显示所有物品的平均格数", { type: "summary", metric: "avgSize", scope: { kind: "all" } }),
  createTool("t63", "风泽中孚", 500, "显示最大格子数的物品平均格数", { type: "summary", metric: "avgSize", scope: { kind: "maxSizeAll" } }),
  createTool("t64", "巽为风", 1000, "显示最高品质的物品平均格数", { type: "summary", metric: "avgSize", scope: { kind: "highestQualityAll" } }),
] as const;

export const FRONT_DEFAULT_SETTINGS = {
  roomName: "",
  maxPlayers: 6,
  password: "",
  totalRounds: 10,
  hintRounds: [1, 3],
  multipliers: [2.0, 1.6, 1.4, 1.2, 1.0],
  initialSpiritStone: 500000,
  entryFee: 10000,
  profitShareRate: 0.35,
  lossRebateRate: 0.25,
  allowDuplicateRoles: true,
  showOtherSpiritStone: true,
  revealBidDisplay: "amount",
  realmProbability: { 炼气: 5, 筑基: 10, 结丹: 15, 元婴: 20, 化神: 20, 炼虚: 15, 合体: 10, 大乘: 5 },
  realmCellSettings: {
    炼气: { min: 10, max: 60, peak: 40, spread: 1.5 },
    筑基: { min: 20, max: 80, peak: 50, spread: 1.5 },
    结丹: { min: 30, max: 100, peak: 60, spread: 1.5 },
    元婴: { min: 40, max: 120, peak: 80, spread: 1.5 },
    化神: { min: 50, max: 150, peak: 100, spread: 1.5 },
    炼虚: { min: 60, max: 200, peak: 120, spread: 1.5 },
    合体: { min: 70, max: 250, peak: 140, spread: 1.5 },
    大乘: { min: 80, max: 300, peak: 150, spread: 1.5 },
  },
  qualityProbability: { 凡: 20, 黄: 20, 玄: 20, 地: 15, 天: 15, 圣: 10 },
  pricePreference: { mode: "amount", amountMidpoint: 200000, amountDecay: 0.5, rankMidpoint: 320, rankDecay: 10 },
  shapeWeights: Object.fromEntries(Array.from({ length: 10 }, (_, h) => Array.from({ length: 10 }, (_, w) => [`${w + 1}x${h + 1}`, 1.0])).flat()),
} as const;