export const ITEM_TYPES = ["功法", "丹药", "武器", "符箓", "阵法", "灵植", "灵兽", "杂项"];

export const ITEM_TYPE_IDS = {
  功法: "gf",
  丹药: "dy",
  武器: "wq",
  符箓: "fl",
  阵法: "zf",
  灵植: "lz",
  灵兽: "ls",
  杂项: "zx",
};

export const ITEM_QUALITIES = ["凡", "黄", "玄", "地", "天", "圣"];

export const ITEM_SHAPES = Array.from({ length: 10 }, (_, x) =>
  Array.from({ length: 10 }, (_, y) => `${x + 1}x${y + 1}`),
).flat();

// 类别对应关系（固定）
// 阵法 -> 阵法
// 典籍 -> 杂项
// 符箓 -> 符箓
// 丹药 -> 丹药
// 法器 -> 武器
// 法宝 -> 武器
// 功法神通 -> 功法
//
// 以后新增物品时，直接照着 createItem({...}) 复制一行即可。
// 只需要填写：id、name、price、width、height、quality、type、desc

const createItem = ({ id, name, price, width, height, quality, type, desc }) => ({
  id,
  name,
  price,
  width,
  height,
  size: width * height,
  shape: `${width}x${height}`,
  quality,
  type,
  desc,
});

export const ITEM_CATALOG = [
  // ==================== 功法神通 -> 功法 ====================
  createItem({ id: "gf_001", name: "正阳劲", price: 60, width: 1, height: 1, quality: "凡", type: "功法", desc: "七玄门的基本内功。" }),
  createItem({ id: "gf_002", name: "象甲功", price: 320, width: 1, height: 2, quality: "凡", type: "功法", desc: "分为九层，后期修炼者刀枪不入。" }),
  createItem({ id: "gf_003", name: "眨眼剑法", price: 320, width: 1, height: 2, quality: "凡", type: "功法", desc: "利用各种光线和视觉错误制敌的刺杀秘术。" }),
  createItem({ id: "gf_004", name: "罗烟步", price: 280, width: 1, height: 2, quality: "凡", type: "功法", desc: "轻功，耗费体力，速度极快。" }),
  createItem({ id: "gf_005", name: "龟息功", price: 450, width: 1, height: 2, quality: "黄", type: "功法", desc: "可让气息、心跳降低到极点，进入假死状态。" }),
  createItem({ id: "gf_006", name: "长春功", price: 1800, width: 2, height: 3, quality: "玄", type: "功法", desc: "木属性基础功法，共十三层，包含多种基础法术。" }),
  createItem({ id: "gf_007", name: "火弹术", price: 90, width: 1, height: 1, quality: "凡", type: "功法", desc: "基础法术，高温破坏力强。" }),
  createItem({ id: "gf_008", name: "天眼术", price: 120, width: 1, height: 1, quality: "凡", type: "功法", desc: "基础法术，可观察修为。" }),
  createItem({ id: "gf_009", name: "御风诀", price: 110, width: 1, height: 1, quality: "凡", type: "功法", desc: "基础法术，可增强跳跃与腾挪能力。" }),
  createItem({ id: "gf_010", name: "敛气术", price: 180, width: 1, height: 1, quality: "黄", type: "功法", desc: "隐匿自身气息的法术。" }),
  createItem({ id: "gf_011", name: "青元剑诀", price: 98000, width: 4, height: 5, quality: "天", type: "功法", desc: "玄剑门镇派绝学，包含青元剑芒、护体剑盾、剑影分光术、大庚剑阵、春黎剑阵、青蟠剑阵等。" }),
  createItem({ id: "gf_012", name: "大衍诀", price: 82000, width: 3, height: 4, quality: "天", type: "功法", desc: "大衍神君自创秘术，共七层，专门强大神识、修炼分神之术。" }),
  createItem({ id: "gf_013", name: "三转重元功", price: 36000, width: 3, height: 3, quality: "地", type: "功法", desc: "三次散功压缩真元，可增加结丹几率。" }),
  createItem({ id: "gf_014", name: "素女轮回功", price: 18000, width: 2, height: 3, quality: "地", type: "功法", desc: "可让人春颜永驻，每隔数十年轮回一次。" }),
  createItem({ id: "gf_015", name: "轮回真决", price: 26000, width: 2, height: 3, quality: "地", type: "功法", desc: "南宫婉功法，可以吸取他人修为。" }),
  createItem({ id: "gf_016", name: "玄阴经", price: 58000, width: 3, height: 4, quality: "天", type: "功法", desc: "集合了玄骨创造的强悍秘技。" }),
  createItem({ id: "gf_017", name: "托天魔功", price: 42000, width: 3, height: 4, quality: "天", type: "功法", desc: "乱星海防御第一魔功，运行时浑身长满金色鳞片。" }),
  createItem({ id: "gf_018", name: "梵圣真魔功", price: 98000, width: 4, height: 5, quality: "天", type: "功法", desc: "结合明王诀与托天魔功的高级功法。" }),
  createItem({ id: "gf_019", name: "血影遁", price: 24000, width: 2, height: 2, quality: "地", type: "功法", desc: "借助精血力量瞬间逃匿百里之外的诡异遁术。" }),
  createItem({ id: "gf_020", name: "疾风九变", price: 16000, width: 2, height: 2, quality: "玄", type: "功法", desc: "妖族功法，禽类妖兽修炼。" }),
  createItem({ id: "gf_021", name: "明王诀", price: 56000, width: 3, height: 4, quality: "天", type: "功法", desc: "佛门顶阶功法，注重修炼法体。" }),
  createItem({ id: "gf_022", name: "元磁神光", price: 128000, width: 4, height: 4, quality: "圣", type: "功法", desc: "乱星海顶级功法，号称克尽天下五行。" }),
  createItem({ id: "gf_023", name: "四煞化甲术", price: 26000, width: 2, height: 3, quality: "地", type: "功法", desc: "凝结煞气为甲的护身秘术。" }),
  createItem({ id: "gf_024", name: "祭雷术", price: 28000, width: 2, height: 3, quality: "地", type: "功法", desc: "专门驱动辟邪神雷的雷系秘术。" }),
  createItem({ id: "gf_025", name: "灵漩邪光", price: 36000, width: 3, height: 3, quality: "地", type: "功法", desc: "可反弹攻击并一定程度无视禁制的诡异神通。" }),
  createItem({ id: "gf_026", name: "玄天炼器术", price: 62000, width: 3, height: 4, quality: "天", type: "功法", desc: "炼制顶级法宝的高深法门。" }),
  createItem({ id: "gf_027", name: "乾蓝冰焰", price: 38000, width: 3, height: 3, quality: "地", type: "功法", desc: "小极宫三大寒焰之一，至阴至寒。" }),
  createItem({ id: "gf_028", name: "黑水冰焰", price: 26000, width: 2, height: 3, quality: "地", type: "功法", desc: "小极宫三大寒焰之一。" }),
  createItem({ id: "gf_029", name: "风离冰焰", price: 26000, width: 2, height: 3, quality: "地", type: "功法", desc: "小极宫三大寒焰之一。" }),
  createItem({ id: "gf_030", name: "缩地术", price: 42000, width: 2, height: 3, quality: "天", type: "功法", desc: "元婴后期修士掌握的高阶遁术。" }),
  createItem({ id: "gf_031", name: "逆灵归元决", price: 36000, width: 3, height: 3, quality: "地", type: "功法", desc: "后天培养本命云兽的秘法。" }),
  createItem({ id: "gf_032", name: "太乙青光", price: 46000, width: 3, height: 3, quality: "天", type: "功法", desc: "天然形成的犀利青光。" }),
  createItem({ id: "gf_033", name: "炼神术", price: 140000, width: 4, height: 5, quality: "圣", type: "功法", desc: "增加神识的真仙界禁术。" }),
  createItem({ id: "gf_034", name: "七鬼噬魂大法", price: 18000, width: 2, height: 3, quality: "地", type: "功法", desc: "以身饲鬼，换取暂时法力。" }),
  createItem({ id: "gf_035", name: "血箭阴魂咒", price: 7200, width: 2, height: 2, quality: "玄", type: "功法", desc: "诅咒使人衰老。" }),
  createItem({ id: "gf_036", name: "控神术", price: 3200, width: 2, height: 2, quality: "玄", type: "功法", desc: "控制凡人服从命令。" }),
  createItem({ id: "gf_037", name: "土牢术", price: 2600, width: 2, height: 2, quality: "玄", type: "功法", desc: "困敌法术。" }),

  // ==================== 丹药 -> 丹药 ====================
  createItem({ id: "dy_001", name: "黄龙丹", price: 260, width: 1, height: 1, quality: "凡", type: "丹药", desc: "炼气期十层以下服用有奇效。" }),
  createItem({ id: "dy_002", name: "金髓丸", price: 260, width: 1, height: 1, quality: "凡", type: "丹药", desc: "炼气期十层以下服用有奇效。" }),
  createItem({ id: "dy_003", name: "合气丹", price: 900, width: 1, height: 1, quality: "黄", type: "丹药", desc: "适合筑基期境界的灵药。" }),
  createItem({ id: "dy_004", name: "辟谷丹", price: 80, width: 1, height: 1, quality: "凡", type: "丹药", desc: "低阶修士服用此丹可以短时间不必进食。" }),
  createItem({ id: "dy_005", name: "定颜丹", price: 8800, width: 1, height: 2, quality: "地", type: "丹药", desc: "用于永驻容貌。" }),
  createItem({ id: "dy_006", name: "筑基丹", price: 3200, width: 1, height: 1, quality: "玄", type: "丹药", desc: "升仙丸，用于突破瓶颈筑基。" }),
  createItem({ id: "dy_007", name: "饲灵丸", price: 1600, width: 1, height: 1, quality: "玄", type: "丹药", desc: "古修士专门用来饲养培育灵兽的灵药。" }),
  createItem({ id: "dy_008", name: "真元丹", price: 1500, width: 1, height: 1, quality: "玄", type: "丹药", desc: "适合筑基中期修士增进修为的丹药。" }),
  createItem({ id: "dy_009", name: "聚灵丹", price: 1200, width: 1, height: 1, quality: "玄", type: "丹药", desc: "适合筑基期修士增进修为的丹药。" }),
  createItem({ id: "dy_010", name: "炼气散", price: 900, width: 1, height: 1, quality: "黄", type: "丹药", desc: "适合筑基期修士增进修为的丹药。" }),
  createItem({ id: "dy_011", name: "补天丹", price: 38000, width: 2, height: 2, quality: "天", type: "丹药", desc: "可弥补灵根的不纯，精炼先天灵根。" }),
  createItem({ id: "dy_012", name: "降尘丹", price: 15000, width: 2, height: 2, quality: "地", type: "丹药", desc: "具有增加结丹几率的灵丹。" }),
  createItem({ id: "dy_013", name: "定灵丹", price: 18000, width: 2, height: 2, quality: "地", type: "丹药", desc: "又叫安魂丹，可以增进修为，还可以定心安魂。" }),
  createItem({ id: "dy_014", name: "长生丹", price: 28000, width: 2, height: 2, quality: "天", type: "丹药", desc: "用寿元果炼制的灵丹，可增加寿元。" }),
  createItem({ id: "dy_015", name: "增元丹", price: 16000, width: 2, height: 2, quality: "地", type: "丹药", desc: "适合结丹期服用的提升修为灵丹。" }),
  createItem({ id: "dy_016", name: "九曲灵参丹", price: 52000, width: 2, height: 3, quality: "天", type: "丹药", desc: "以九曲灵参、玛瑙角、千叶露为原料炼制而成，用于增加结婴几率。" }),
  createItem({ id: "dy_017", name: "造化丹", price: 48000, width: 2, height: 3, quality: "天", type: "丹药", desc: "服用后堕入幻境体验境界，对突破境界有奇效。" }),
  createItem({ id: "dy_018", name: "绎云丹", price: 24000, width: 2, height: 2, quality: "地", type: "丹药", desc: "适合元婴中期提升修为的丹药。" }),
  createItem({ id: "dy_019", name: "雪魄丸", price: 18000, width: 2, height: 2, quality: "地", type: "丹药", desc: "修炼冰寒属性功法的修士辅助灵药。" }),
  createItem({ id: "dy_020", name: "昊元丹", price: 16000, width: 2, height: 2, quality: "地", type: "丹药", desc: "结丹期修士突破瓶颈增进修为的灵丹。" }),
  createItem({ id: "dy_021", name: "培婴丹", price: 42000, width: 2, height: 3, quality: "天", type: "丹药", desc: "可洗筋易髓，壮大元婴，使人更容易突破修炼瓶颈。" }),
  createItem({ id: "dy_022", name: "清虚丹", price: 12000, width: 1, height: 2, quality: "地", type: "丹药", desc: "可以使灵兽保持神智的丹药。" }),
  createItem({ id: "dy_023", name: "血气丹", price: 22000, width: 2, height: 2, quality: "地", type: "丹药", desc: "可使化神期修士寿元延长数十年的丹药。" }),
  createItem({ id: "dy_024", name: "紫阴丸", price: 18000, width: 1, height: 2, quality: "地", type: "丹药", desc: "可制衡龙吟之质的丹药。" }),
  createItem({ id: "dy_025", name: "碧焰酒", price: 9000, width: 1, height: 2, quality: "玄", type: "丹药", desc: "裂风兽酿制的灵酒。" }),
  createItem({ id: "dy_026", name: "雾雨灵茶", price: 1500, width: 1, height: 1, quality: "黄", type: "丹药", desc: "天机阁招待客人的灵茶。" }),
  createItem({ id: "dy_027", name: "万年灵乳", price: 52000, width: 2, height: 2, quality: "天", type: "丹药", desc: "喝一滴可以瞬间回复全部法力的灵液。" }),
  createItem({ id: "dy_028", name: "明清灵水", price: 22000, width: 1, height: 2, quality: "地", type: "丹药", desc: "用此水擦拭双目，可以产生明清灵眼神通。" }),
  createItem({ id: "dy_029", name: "回阳真水", price: 62000, width: 2, height: 3, quality: "天", type: "丹药", desc: "白骨生肉的秘药，可延长修士四分之一寿元。" }),
  createItem({ id: "dy_030", name: "灭尘丹", price: 18000, width: 1, height: 2, quality: "地", type: "丹药", desc: "让飞升灵界的修士去除异界气息。" }),
  createItem({ id: "dy_031", name: "腾龙丹", price: 34000, width: 2, height: 2, quality: "天", type: "丹药", desc: "以芝龙果为主料炼制。" }),
  createItem({ id: "dy_032", name: "虚灵丹", price: 86000, width: 3, height: 3, quality: "圣", type: "丹药", desc: "太虚妙灵丹，可极大增加高阶突破几率。" }),
  createItem({ id: "dy_033", name: "清灵散", price: 220, width: 1, height: 1, quality: "凡", type: "丹药", desc: "解毒与疗伤丹散。" }),
  createItem({ id: "dy_034", name: "养精丹", price: 260, width: 1, height: 1, quality: "凡", type: "丹药", desc: "疗伤补气的低阶丹药。" }),
  createItem({ id: "dy_035", name: "百草丹", price: 320, width: 1, height: 1, quality: "黄", type: "丹药", desc: "草木精华炼成的疗伤丹药。" }),
  createItem({ id: "dy_036", name: "还梦丹", price: 600, width: 1, height: 1, quality: "黄", type: "丹药", desc: "用于安神定魄和恢复心神。" }),
  createItem({ id: "dy_037", name: "血肢丹", price: 800, width: 1, height: 1, quality: "黄", type: "丹药", desc: "疗伤断肢相关灵丹。" }),
  createItem({ id: "dy_038", name: "腐心丸", price: 900, width: 1, height: 1, quality: "黄", type: "丹药", desc: "阴毒控制类药丸。" }),
  createItem({ id: "dy_039", name: "抽髓丸", price: 1200, width: 1, height: 1, quality: "玄", type: "丹药", desc: "阴狠霸道的毒药。" }),
  createItem({ id: "dy_040", name: "尸虫丸", price: 1600, width: 1, height: 1, quality: "玄", type: "丹药", desc: "用于控制与蛊毒的邪门药丸。" }),
  createItem({ id: "dy_041", name: "断魂丹", price: 2000, width: 1, height: 1, quality: "玄", type: "丹药", desc: "可伤神魂的毒丹。" }),
  createItem({ id: "dy_042", name: "笑魂散", price: 2200, width: 1, height: 1, quality: "玄", type: "丹药", desc: "作用于神识魂魄的古怪毒散。" }),
  createItem({ id: "dy_043", name: "至元丹", price: 22000, width: 2, height: 2, quality: "地", type: "丹药", desc: "较高阶的修为提升丹药。" }),
  createItem({ id: "dy_044", name: "幻灭丹", price: 24000, width: 2, height: 2, quality: "地", type: "丹药", desc: "突破瓶颈类丹药。" }),
  createItem({ id: "dy_045", name: "天心丹", price: 22000, width: 2, height: 2, quality: "地", type: "丹药", desc: "偏向神识与精神稳固的丹药。" }),
  createItem({ id: "dy_046", name: "蕴念珠", price: 26000, width: 2, height: 2, quality: "地", type: "丹药", desc: "用于养神蕴念之物。" }),
  createItem({ id: "dy_047", name: "血阳丹", price: 30000, width: 2, height: 2, quality: "天", type: "丹药", desc: "高阶增益型丹药。" }),
  createItem({ id: "dy_048", name: "玉清丹", price: 32000, width: 2, height: 2, quality: "天", type: "丹药", desc: "高阶修士服用的精纯灵丹。" }),
  createItem({ id: "dy_049", name: "真蟾液", price: 36000, width: 2, height: 2, quality: "天", type: "丹药", desc: "高阶灵液。" }),
  createItem({ id: "dy_050", name: "焕心丹", price: 34000, width: 2, height: 2, quality: "天", type: "丹药", desc: "恢复心脉与神魂的高阶丹药。" }),
  createItem({ id: "dy_051", name: "魔炼天元丹", price: 46000, width: 2, height: 3, quality: "天", type: "丹药", desc: "极高阶魔道丹药。" }),
  createItem({ id: "dy_052", name: "雷髓丹", price: 42000, width: 2, height: 3, quality: "天", type: "丹药", desc: "雷属性修士珍视的高阶丹药。" }),
  createItem({ id: "dy_053", name: "万妙丹", price: 50000, width: 2, height: 3, quality: "天", type: "丹药", desc: "高阶综合增益灵丹。" }),
  createItem({ id: "dy_054", name: "长元丹", price: 72000, width: 3, height: 3, quality: "圣", type: "丹药", desc: "极品丹药，可大幅延长元气与修行底蕴。" }),

  // ==================== 符箓 -> 符箓 ====================
  createItem({ id: "fl_001", name: "平安符", price: 30, width: 1, height: 1, quality: "凡", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_002", name: "隐身符", price: 180, width: 1, height: 1, quality: "黄", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_003", name: "遁地符", price: 220, width: 1, height: 1, quality: "黄", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_004", name: "连珠雷符", price: 260, width: 1, height: 1, quality: "黄", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_005", name: "冰弹符", price: 60, width: 1, height: 1, quality: "凡", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_006", name: "火弹符", price: 60, width: 1, height: 1, quality: "凡", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_007", name: "定神符", price: 80, width: 1, height: 1, quality: "凡", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_008", name: "传音符", price: 40, width: 1, height: 1, quality: "凡", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_009", name: "遁形符", price: 180, width: 1, height: 1, quality: "黄", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_010", name: "飞天符", price: 220, width: 1, height: 1, quality: "黄", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_011", name: "回春符", price: 150, width: 1, height: 1, quality: "黄", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_012", name: "火云符", price: 180, width: 1, height: 1, quality: "黄", type: "符箓", desc: "初级符箓。" }),
  createItem({ id: "fl_013", name: "小五行符", price: 800, width: 1, height: 1, quality: "玄", type: "符箓", desc: "中级符箓。" }),
  createItem({ id: "fl_014", name: "融灵符", price: 680, width: 1, height: 1, quality: "玄", type: "符箓", desc: "中级符箓。" }),
  createItem({ id: "fl_015", name: "巨力符", price: 520, width: 1, height: 1, quality: "玄", type: "符箓", desc: "中级符箓。" }),
  createItem({ id: "fl_016", name: "隔音符", price: 260, width: 1, height: 1, quality: "黄", type: "符箓", desc: "中级符箓。" }),
  createItem({ id: "fl_017", name: "水牢符", price: 620, width: 1, height: 1, quality: "玄", type: "符箓", desc: "中级符箓。" }),
  createItem({ id: "fl_018", name: "火鸟符", price: 720, width: 1, height: 1, quality: "玄", type: "符箓", desc: "中级符箓。" }),
  createItem({ id: "fl_019", name: "陷地符", price: 680, width: 1, height: 1, quality: "玄", type: "符箓", desc: "中级符箓。" }),
  createItem({ id: "fl_020", name: "灵隐符", price: 2200, width: 1, height: 1, quality: "地", type: "符箓", desc: "高级符箓。" }),
  createItem({ id: "fl_021", name: "敛息符", price: 1800, width: 1, height: 1, quality: "玄", type: "符箓", desc: "高级符箓。" }),
  createItem({ id: "fl_022", name: "镇魂符", price: 2800, width: 1, height: 1, quality: "地", type: "符箓", desc: "高级符箓。" }),
  createItem({ id: "fl_023", name: "传送符", price: 4200, width: 1, height: 1, quality: "地", type: "符箓", desc: "高级符箓。" }),
  createItem({ id: "fl_024", name: "化灵符", price: 3200, width: 1, height: 1, quality: "地", type: "符箓", desc: "高级符箓。" }),
  createItem({ id: "fl_025", name: "六丁天甲符", price: 12000, width: 1, height: 2, quality: "天", type: "符箓", desc: "高级符箓。" }),
  createItem({ id: "fl_026", name: "降灵符", price: 2600, width: 1, height: 1, quality: "地", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_027", name: "灭魂符", price: 5200, width: 1, height: 1, quality: "地", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_028", name: "破界符", price: 18000, width: 1, height: 2, quality: "天", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_029", name: "万里符", price: 6000, width: 1, height: 1, quality: "地", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_030", name: "太一化清符", price: 22000, width: 1, height: 2, quality: "天", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_031", name: "傀儡符", price: 2400, width: 1, height: 1, quality: "地", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_032", name: "九宫天乾符", price: 18000, width: 1, height: 2, quality: "天", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_033", name: "甲元符", price: 1200, width: 1, height: 1, quality: "玄", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_034", name: "天空符", price: 3200, width: 1, height: 1, quality: "地", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_035", name: "空明符", price: 3600, width: 1, height: 1, quality: "地", type: "符箓", desc: "特殊符箓。" }),
  createItem({ id: "fl_036", name: "玄化封灵符", price: 42000, width: 2, height: 2, quality: "天", type: "符箓", desc: "真仙界符箓。" }),
  createItem({ id: "fl_037", name: "三清雷霄符", price: 68000, width: 2, height: 2, quality: "圣", type: "符箓", desc: "真仙界符箓。" }),
  createItem({ id: "fl_038", name: "金品替身仙符", price: 98000, width: 2, height: 3, quality: "圣", type: "符箓", desc: "真仙界符箓。" }),
  createItem({ id: "fl_039", name: "避风符", price: 22000, width: 1, height: 2, quality: "天", type: "符箓", desc: "真仙界符箓。" }),
  createItem({ id: "fl_040", name: "桃僵李代符", price: 38000, width: 2, height: 2, quality: "天", type: "符箓", desc: "真仙界符箓。" }),
  createItem({ id: "fl_041", name: "分灵符", price: 26000, width: 2, height: 2, quality: "天", type: "符箓", desc: "真仙界符箓。" }),
  createItem({ id: "fl_042", name: "符宝", price: 18000, width: 2, height: 2, quality: "地", type: "符箓", desc: "结丹期以上修士才可制作，兼具符箓和法宝特性。" }),

  // ==================== 阵法 -> 阵法 ====================
  createItem({ id: "zf_001", name: "古传送阵", price: 42000, width: 3, height: 3, quality: "天", type: "阵法", desc: "能够进行超远距离传送。" }),
  createItem({ id: "zf_002", name: "单向传送阵", price: 12000, width: 2, height: 2, quality: "地", type: "阵法", desc: "仅需要传送端，无需接收端。" }),
  createItem({ id: "zf_003", name: "临时传送阵", price: 5200, width: 2, height: 2, quality: "玄", type: "阵法", desc: "仅能使用一次的传送阵。" }),
  createItem({ id: "zf_004", name: "风炎龙烈阵", price: 46000, width: 3, height: 4, quality: "天", type: "阵法", desc: "攻击型法阵，威力巨大。" }),
  createItem({ id: "zf_005", name: "冰魄寒烈阵", price: 52000, width: 3, height: 4, quality: "天", type: "阵法", desc: "上古法阵，由万年玄冰柱组成。" }),
  createItem({ id: "zf_006", name: "风火天绝阵", price: 24000, width: 3, height: 3, quality: "地", type: "阵法", desc: "由风火铜柱组成，用于围困。" }),
  createItem({ id: "zf_007", name: "上元灭光阵", price: 68000, width: 4, height: 4, quality: "天", type: "阵法", desc: "阗天城的护城大阵。" }),
  createItem({ id: "zf_008", name: "九阳罡日法阵", price: 56000, width: 3, height: 4, quality: "天", type: "阵法", desc: "吸纳天地阳力，提升防御力。" }),
  createItem({ id: "zf_009", name: "颠倒五行阵", price: 22000, width: 2, height: 3, quality: "地", type: "阵法", desc: "小禁断之阵，用于迷惑和困敌。" }),
  createItem({ id: "zf_010", name: "四煞阵", price: 16000, width: 2, height: 3, quality: "地", type: "阵法", desc: "抵御魔道的防守法阵。" }),
  createItem({ id: "zf_011", name: "四象阵", price: 12000, width: 2, height: 2, quality: "玄", type: "阵法", desc: "用于困敌。" }),
  createItem({ id: "zf_012", name: "五行使踪阵", price: 22000, width: 2, height: 3, quality: "地", type: "阵法", desc: "幻术法阵，用于困敌。" }),
  createItem({ id: "zf_013", name: "幻光玄天阵", price: 58000, width: 3, height: 4, quality: "天", type: "阵法", desc: "用于困制冰凤。" }),
  createItem({ id: "zf_014", name: "万魂大阵", price: 42000, width: 3, height: 4, quality: "天", type: "阵法", desc: "鬼灵门大阵，可能用于控制或召唤魂魄。" }),
  createItem({ id: "zf_015", name: "两仪微尘阵", price: 120000, width: 5, height: 5, quality: "圣", type: "阵法", desc: "仙界法阵，具有困敌、削弱、自爆功能。" }),
  createItem({ id: "zf_016", name: "青真琉光大阵", price: 62000, width: 4, height: 4, quality: "天", type: "阵法", desc: "上古秘阵，擅于困敌。" }),
  createItem({ id: "zf_017", name: "小须弥金刚阵", price: 52000, width: 3, height: 4, quality: "天", type: "阵法", desc: "佛宗法阵，坚固难破。" }),
  createItem({ id: "zf_018", name: "上古封印法阵", price: 72000, width: 4, height: 4, quality: "天", type: "阵法", desc: "以七灵岛为阵眼的封印阵。" }),
  createItem({ id: "zf_019", name: "血咒之门", price: 62000, width: 3, height: 4, quality: "天", type: "阵法", desc: "封印血焰主魂。" }),
  createItem({ id: "zf_020", name: "太妙神禁", price: 140000, width: 5, height: 5, quality: "圣", type: "阵法", desc: "十大古禁之一。" }),
  createItem({ id: "zf_021", name: "八元锁魂阵", price: 150000, width: 5, height: 5, quality: "圣", type: "阵法", desc: "真仙界阵法，用于封印强大生物。" }),
  createItem({ id: "zf_022", name: "控神法阵", price: 9000, width: 2, height: 2, quality: "玄", type: "阵法", desc: "用于灵虫认主的仪式。" }),
  createItem({ id: "zf_023", name: "天罡罩", price: 18000, width: 2, height: 3, quality: "地", type: "阵法", desc: "上古禁制，用于特定地点的保护。" }),
  createItem({ id: "zf_024", name: "拘灵阵", price: 6200, width: 2, height: 2, quality: "玄", type: "阵法", desc: "可以掩饰灵气的阵法。" }),
  createItem({ id: "zf_025", name: "转轮聚阴阵", price: 12000, width: 2, height: 3, quality: "地", type: "阵法", desc: "用于聚集阴气。" }),
  createItem({ id: "zf_026", name: "御雷万封大阵", price: 82000, width: 4, height: 4, quality: "天", type: "阵法", desc: "用于限制万灵行动。" }),
  createItem({ id: "zf_027", name: "千年一梦飘渺大阵", price: 160000, width: 5, height: 5, quality: "圣", type: "阵法", desc: "仙界著名阵法，让人陷入无法自拔的幻境。" }),
  createItem({ id: "zf_028", name: "天风狂烈阵", price: 6800, width: 2, height: 2, quality: "玄", type: "阵法", desc: "范围广，使筑基期修士头疼。" }),
  createItem({ id: "zf_029", name: "幻行天罗阵", price: 7200, width: 2, height: 2, quality: "玄", type: "阵法", desc: "范围广，影响筑基期修士。" }),
  createItem({ id: "zf_030", name: "六遁水波阵", price: 18000, width: 2, height: 3, quality: "地", type: "阵法", desc: "需多人主持，既可困敌又可伤敌。" }),
  createItem({ id: "zf_031", name: "北斗两仪阵", price: 22000, width: 2, height: 3, quality: "地", type: "阵法", desc: "按特定规律排列，形成北斗形状的阵势。" }),
  createItem({ id: "zf_032", name: "四象玄武阵", price: 18000, width: 2, height: 3, quality: "地", type: "阵法", desc: "土属性法阵，强化地形硬度。" }),
  createItem({ id: "zf_033", name: "浑天两仪阵", price: 56000, width: 3, height: 4, quality: "天", type: "阵法", desc: "消除合体期修士战斗的动静。" }),
  createItem({ id: "zf_034", name: "黄沙阵", price: 2400, width: 2, height: 2, quality: "黄", type: "阵法", desc: "黄沙类困敌阵法。" }),
  createItem({ id: "zf_035", name: "黄泉鬼阵", price: 22000, width: 2, height: 3, quality: "地", type: "阵法", desc: "鬼道阵法。" }),
  createItem({ id: "zf_036", name: "八极分光阵", price: 42000, width: 3, height: 3, quality: "天", type: "阵法", desc: "高阶分光杀阵。" }),

  // ==================== 灵植 -> 灵植 ====================
  createItem({ id: "lz_001", name: "玉髓芝", price: 1800, width: 1, height: 2, quality: "玄", type: "灵植", desc: "炼制筑基丹的主原料。" }),
  createItem({ id: "lz_002", name: "紫猴花", price: 1800, width: 1, height: 2, quality: "玄", type: "灵植", desc: "炼制筑基丹的主原料。" }),
  createItem({ id: "lz_003", name: "天灵果", price: 2400, width: 1, height: 2, quality: "玄", type: "灵植", desc: "炼制筑基丹的主原料。" }),
  createItem({ id: "lz_004", name: "七星草", price: 600, width: 1, height: 2, quality: "黄", type: "灵植", desc: "制作符纸的材料。" }),
  createItem({ id: "lz_005", name: "龙鳞果", price: 26000, width: 2, height: 2, quality: "地", type: "灵植", desc: "仙家之果，据说服用之人可以脱胎换骨。" }),
  createItem({ id: "lz_006", name: "霓裳草", price: 4200, width: 1, height: 2, quality: "玄", type: "灵植", desc: "别名诱妖草，能吸引八级以下妖兽。" }),
  createItem({ id: "lz_007", name: "七霞莲", price: 38000, width: 2, height: 3, quality: "天", type: "灵植", desc: "凡人服用可以起死回生，修仙者服下可修为大涨。" }),
  createItem({ id: "lz_008", name: "九曲灵参", price: 48000, width: 2, height: 3, quality: "天", type: "灵植", desc: "天地灵气所化灵草，灵性十足，可自行活动。" }),
  createItem({ id: "lz_009", name: "寿元果", price: 26000, width: 2, height: 2, quality: "地", type: "灵植", desc: "可炼制长生丹，增加寿元。" }),
  createItem({ id: "lz_010", name: "天青花", price: 4800, width: 1, height: 2, quality: "玄", type: "灵植", desc: "可以暂时强行提高妖兽道行，有副作用。" }),
  createItem({ id: "lz_011", name: "金阳芝", price: 12000, width: 2, height: 2, quality: "地", type: "灵植", desc: "火属性灵草，是炼制火属性灵丹的顶阶材料。" }),
  createItem({ id: "lz_012", name: "天元果", price: 18000, width: 2, height: 2, quality: "地", type: "灵植", desc: "吃一颗就可延寿百年的灵果。" }),
  createItem({ id: "lz_013", name: "补天芝", price: 22000, width: 2, height: 2, quality: "地", type: "灵植", desc: "紫色灵芝，生吃即可精进数十年苦修。" }),
  createItem({ id: "lz_014", name: "菩提花", price: 26000, width: 2, height: 2, quality: "地", type: "灵植", desc: "果实可解封魂咒。" }),
  createItem({ id: "lz_015", name: "火精枣", price: 12000, width: 2, height: 2, quality: "地", type: "灵植", desc: "可利用火灵力强行突破功法瓶颈，但有危险。" }),
  createItem({ id: "lz_016", name: "玄冰花", price: 12000, width: 1, height: 2, quality: "地", type: "灵植", desc: "炼制玄冰丹的主原料。" }),
  createItem({ id: "lz_017", name: "冰灵果", price: 8600, width: 1, height: 2, quality: "玄", type: "灵植", desc: "果中含有极其精纯的冰寒灵力。" }),
  createItem({ id: "lz_018", name: "天雷竹", price: 52000, width: 2, height: 4, quality: "天", type: "灵植", desc: "三大神木之一，万年天雷竹称为金雷竹。" }),
  createItem({ id: "lz_019", name: "养魂木", price: 62000, width: 2, height: 4, quality: "天", type: "灵植", desc: "三大神木之一，可以滋养魂魄元神。" }),
  createItem({ id: "lz_020", name: "灵眼之树", price: 72000, width: 3, height: 5, quality: "天", type: "灵植", desc: "三大神木之一，可流出醇液。" }),

  // ==================== 灵兽 -> 灵兽 ====================
  createItem({ id: "ls_001", name: "墨蛟", price: 18000, width: 4, height: 2, quality: "地", type: "灵兽", desc: "黑黝黝、浑身长着巨大鳞甲的蛇形妖物。" }),
  createItem({ id: "ls_002", name: "脂阳鸟", price: 12000, width: 2, height: 2, quality: "地", type: "灵兽", desc: "诞生于精火之中，专爱食用各种阴鬼厉魄。" }),
  createItem({ id: "ls_003", name: "血玉蜘蛛", price: 22000, width: 2, height: 2, quality: "地", type: "灵兽", desc: "曾帮助韩立取得虚天鼎。" }),
  createItem({ id: "ls_004", name: "啼魂兽", price: 96000, width: 3, height: 4, quality: "圣", type: "灵兽", desc: "可喷出吸魂神光，吞噬精魂、鬼物和尸气。" }),
  createItem({ id: "ls_005", name: "天都妖尸", price: 28000, width: 3, height: 3, quality: "地", type: "灵兽", desc: "极阴修炼天都尸火祭炼出的妖尸。" }),
  createItem({ id: "ls_006", name: "狻猊兽", price: 46000, width: 3, height: 3, quality: "天", type: "灵兽", desc: "万丈海王族妖兽，身怀梵圣真片。" }),
  createItem({ id: "ls_007", name: "雷鹏", price: 68000, width: 4, height: 3, quality: "天", type: "灵兽", desc: "天地灵鸟，飞遁速度极快。" }),
  createItem({ id: "ls_008", name: "尸魈", price: 22000, width: 2, height: 3, quality: "地", type: "灵兽", desc: "怨气不散的高阶炼尸。" }),
  createItem({ id: "ls_009", name: "四瞳灵狐", price: 30000, width: 2, height: 2, quality: "地", type: "灵兽", desc: "雪白灵狐，擅长隐匿、幻术。" }),
  createItem({ id: "ls_010", name: "五行灵婴", price: 42000, width: 2, height: 3, quality: "天", type: "灵兽", desc: "御灵宗用稀有材料和秘术炼制而成。" }),
  createItem({ id: "ls_011", name: "至木灵婴", price: 48000, width: 2, height: 3, quality: "天", type: "灵兽", desc: "五行灵婴之一，后被韩立炼化成第二元婴。" }),
  createItem({ id: "ls_012", name: "青风牛", price: 12000, width: 3, height: 2, quality: "玄", type: "灵兽", desc: "七级妖兽，被天澜圣殿用于圣兽铸体。" }),
  createItem({ id: "ls_013", name: "冰甲蟒", price: 12000, width: 3, height: 2, quality: "玄", type: "灵兽", desc: "七级妖兽，被天澜圣殿用于圣兽铸体。" }),
  createItem({ id: "ls_014", name: "昊阳鸟", price: 24000, width: 2, height: 3, quality: "地", type: "灵兽", desc: "火属性灵禽，岳阳宫的传承灵禽。" }),
  createItem({ id: "ls_015", name: "土甲龙", price: 16000, width: 3, height: 2, quality: "玄", type: "灵兽", desc: "防御极强且擅长寻找天材地宝。" }),
  createItem({ id: "ls_016", name: "金身月尸", price: 62000, width: 3, height: 4, quality: "天", type: "灵兽", desc: "人界最高等阶的炼尸，化神期修为。" }),
  createItem({ id: "ls_017", name: "银翅夜叉", price: 42000, width: 3, height: 4, quality: "天", type: "灵兽", desc: "仅次于金身月尸的炼尸。" }),
  createItem({ id: "ls_018", name: "阴芝马", price: 22000, width: 2, height: 2, quality: "地", type: "灵兽", desc: "其血肉是培婴丹的主原料。" }),
  createItem({ id: "ls_019", name: "孽猿", price: 18000, width: 3, height: 3, quality: "玄", type: "灵兽", desc: "由人的怨念在重阴之地凝结形成。" }),
  createItem({ id: "ls_020", name: "冰凤", price: 82000, width: 4, height: 4, quality: "圣", type: "灵兽", desc: "具真灵天凤部分血脉的天地灵兽后裔。" }),
  createItem({ id: "ls_021", name: "珈轮战魔", price: 36000, width: 3, height: 3, quality: "地", type: "灵兽", desc: "三首形态的古魔。" }),
  createItem({ id: "ls_022", name: "罗睺", price: 160000, width: 5, height: 5, quality: "圣", type: "灵兽", desc: "可吞食日月并破空穿梭于界面间的魔兽。" }),
  createItem({ id: "ls_023", name: "游天鲲鹏", price: 160000, width: 5, height: 5, quality: "圣", type: "灵兽", desc: "罗睺的死敌，天生的风属性妖灵。" }),
  createItem({ id: "ls_024", name: "离火麒麟", price: 140000, width: 5, height: 4, quality: "圣", type: "灵兽", desc: "灵界高阶妖兽，可与罗睺等相媲美。" }),
  createItem({ id: "ls_025", name: "真灵", price: 220000, width: 6, height: 6, quality: "圣", type: "灵兽", desc: "可与大乘存在相提并论的顶级存在。" }),

  // ==================== 法器 / 法宝 -> 武器 ====================
  createItem({ id: "wq_001", name: "神风舟", price: 1800, width: 2, height: 1, quality: "玄", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_002", name: "踏云靴", price: 1600, width: 1, height: 2, quality: "玄", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_003", name: "聚魂钵", price: 5200, width: 2, height: 2, quality: "地", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_004", name: "银丝鼎", price: 3200, width: 2, height: 2, quality: "地", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_005", name: "大挪移令", price: 26000, width: 2, height: 2, quality: "天", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_006", name: "玄玉令牌", price: 2200, width: 1, height: 2, quality: "玄", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_007", name: "雪虹绫", price: 4200, width: 2, height: 2, quality: "地", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_008", name: "月阳宝珠", price: 6200, width: 2, height: 2, quality: "地", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_009", name: "风云幡", price: 5200, width: 2, height: 3, quality: "地", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_010", name: "镇海钟", price: 12000, width: 2, height: 3, quality: "天", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_011", name: "破禁珠", price: 18000, width: 2, height: 2, quality: "天", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_012", name: "万灵伞", price: 16000, width: 2, height: 3, quality: "天", type: "武器", desc: "辅助类法器。" }),
  createItem({ id: "wq_013", name: "金蚨子母刃", price: 2600, width: 2, height: 2, quality: "玄", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_014", name: "玄铁飞天盾", price: 2400, width: 2, height: 2, quality: "玄", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_015", name: "青蛟旗", price: 5200, width: 2, height: 3, quality: "地", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_016", name: "乌龙夺", price: 1800, width: 1, height: 2, quality: "玄", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_017", name: "无形针", price: 2600, width: 1, height: 2, quality: "地", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_018", name: "天雷子", price: 6200, width: 1, height: 1, quality: "地", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_019", name: "五行罩", price: 3600, width: 2, height: 2, quality: "地", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_020", name: "金罡灭魔雷", price: 12000, width: 1, height: 1, quality: "天", type: "武器", desc: "攻防类法器。" }),
  createItem({ id: "wq_021", name: "升仙令", price: 26000, width: 2, height: 2, quality: "天", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_022", name: "金阙玉书", price: 72000, width: 3, height: 4, quality: "天", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_023", name: "天机府", price: 42000, width: 4, height: 4, quality: "天", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_024", name: "九霄殿", price: 56000, width: 4, height: 4, quality: "天", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_025", name: "须弥芥子空间", price: 120000, width: 5, height: 5, quality: "圣", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_026", name: "化龙玺", price: 38000, width: 3, height: 3, quality: "天", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_027", name: "血魂瓶", price: 18000, width: 2, height: 2, quality: "地", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_028", name: "血晶棺", price: 32000, width: 3, height: 4, quality: "天", type: "武器", desc: "功能类法器。" }),
  createItem({ id: "wq_029", name: "引魂钟", price: 5200, width: 2, height: 2, quality: "地", type: "武器", desc: "伙伴类法器。" }),
  createItem({ id: "wq_030", name: "魔尘幡", price: 12000, width: 2, height: 3, quality: "地", type: "武器", desc: "功能不详类法器。" }),
  createItem({ id: "wq_031", name: "青蝉钟", price: 8800, width: 2, height: 2, quality: "地", type: "武器", desc: "功能不详类法器。" }),
  createItem({ id: "wq_032", name: "血魔剑", price: 22000, width: 2, height: 3, quality: "天", type: "武器", desc: "魔器。" }),
  createItem({ id: "wq_033", name: "魔龙刃", price: 62000, width: 3, height: 4, quality: "天", type: "武器", desc: "魔器。" }),
  createItem({ id: "wq_034", name: "三神白骨幡", price: 32000, width: 3, height: 4, quality: "天", type: "武器", desc: "魔器。" }),
  createItem({ id: "wq_035", name: "分界镜", price: 26000, width: 2, height: 2, quality: "天", type: "武器", desc: "魔器。" }),
  createItem({ id: "wq_036", name: "封仙珠", price: 120000, width: 4, height: 4, quality: "圣", type: "武器", desc: "仙器。" }),
  createItem({ id: "wq_037", name: "仙牌", price: 86000, width: 3, height: 3, quality: "圣", type: "武器", desc: "仙器。" }),
  createItem({ id: "wq_038", name: "摄灵天网", price: 96000, width: 4, height: 4, quality: "圣", type: "武器", desc: "仙器。" }),
  createItem({ id: "wq_039", name: "斩元仙剑", price: 150000, width: 5, height: 5, quality: "圣", type: "武器", desc: "仙器。" }),
  createItem({ id: "wq_040", name: "蛟纹长剑", price: 6800, width: 2, height: 2, quality: "地", type: "武器", desc: "灵具。" }),
  createItem({ id: "wq_041", name: "金莹剑", price: 7200, width: 2, height: 2, quality: "地", type: "武器", desc: "灵具。" }),
  createItem({ id: "wq_042", name: "辟火宝衣", price: 16000, width: 2, height: 3, quality: "地", type: "武器", desc: "辅助类法宝。" }),
  createItem({ id: "wq_043", name: "寒冰珠", price: 16000, width: 2, height: 2, quality: "地", type: "武器", desc: "辅助类法宝。" }),
  createItem({ id: "wq_044", name: "风雷翅", price: 78000, width: 3, height: 4, quality: "天", type: "武器", desc: "辅助类法宝。" }),
  createItem({ id: "wq_045", name: "七真宝", price: 52000, width: 4, height: 4, quality: "天", type: "武器", desc: "辅助类法宝。" }),
  createItem({ id: "wq_046", name: "逆星盘", price: 32000, width: 3, height: 3, quality: "天", type: "武器", desc: "辅助类法宝。" }),
  createItem({ id: "wq_047", name: "金雷剑", price: 42000, width: 3, height: 3, quality: "天", type: "武器", desc: "攻防类法宝。" }),
  createItem({ id: "wq_048", name: "皇麟甲", price: 32000, width: 3, height: 3, quality: "天", type: "武器", desc: "攻防类法宝。" }),
  createItem({ id: "wq_049", name: "朱雀环", price: 26000, width: 2, height: 2, quality: "天", type: "武器", desc: "攻防类法宝。" }),
  createItem({ id: "wq_050", name: "青龙追魂锁", price: 36000, width: 3, height: 3, quality: "天", type: "武器", desc: "攻防类法宝。" }),
  createItem({ id: "wq_051", name: "青冥针符宝", price: 18000, width: 1, height: 2, quality: "地", type: "武器", desc: "符宝类。" }),
  createItem({ id: "wq_052", name: "蓝色蛟龙符宝", price: 28000, width: 2, height: 3, quality: "天", type: "武器", desc: "符宝类。" }),
  createItem({ id: "wq_053", name: "乾坤塔", price: 92000, width: 4, height: 4, quality: "圣", type: "武器", desc: "真宝与升级法宝类。" }),
  createItem({ id: "wq_054", name: "万剑图", price: 52000, width: 4, height: 4, quality: "天", type: "武器", desc: "真宝与升级法宝类。" }),
  createItem({ id: "wq_055", name: "鸣魂珠", price: 22000, width: 2, height: 2, quality: "地", type: "武器", desc: "功能类法宝。" }),
  createItem({ id: "wq_056", name: "摄魂幡", price: 32000, width: 3, height: 3, quality: "天", type: "武器", desc: "功能类法宝。" }),
  createItem({ id: "wq_057", name: "聚灵珠", price: 18000, width: 2, height: 2, quality: "地", type: "武器", desc: "修炼类法宝。" }),
  createItem({ id: "wq_058", name: "光阴之丝", price: 82000, width: 3, height: 3, quality: "圣", type: "武器", desc: "修炼类法宝。" }),
  createItem({ id: "wq_059", name: "花篮古宝", price: 32000, width: 2, height: 3, quality: "天", type: "武器", desc: "古宝与灵宝。" }),
  createItem({ id: "wq_060", name: "玄黄镜", price: 42000, width: 3, height: 3, quality: "天", type: "武器", desc: "古宝与灵宝。" }),
  createItem({ id: "wq_061", name: "千重峰", price: 46000, width: 4, height: 4, quality: "天", type: "武器", desc: "古宝与灵宝。" }),
  createItem({ id: "wq_062", name: "太玄八卦图", price: 52000, width: 4, height: 4, quality: "天", type: "武器", desc: "古宝与灵宝。" }),
  createItem({ id: "wq_063", name: "玄天之宝", price: 180000, width: 5, height: 5, quality: "圣", type: "武器", desc: "古宝与灵宝。" }),
  createItem({ id: "wq_064", name: "混沌万灵榜", price: 170000, width: 5, height: 5, quality: "圣", type: "武器", desc: "古宝与灵宝。" }),
  createItem({ id: "wq_065", name: "混魔旗", price: 42000, width: 3, height: 4, quality: "天", type: "武器", desc: "魔宝。" }),
  createItem({ id: "wq_066", name: "子母真魔幡", price: 62000, width: 4, height: 4, quality: "天", type: "武器", desc: "魔宝。" }),
  createItem({ id: "wq_067", name: "玄天如意刃", price: 120000, width: 5, height: 5, quality: "圣", type: "武器", desc: "魔宝。" }),
  createItem({ id: "wq_068", name: "玄天花树", price: 128000, width: 5, height: 5, quality: "圣", type: "武器", desc: "魔宝。" }),
  createItem({ id: "wq_069", name: "玄天黑戈", price: 140000, width: 5, height: 5, quality: "圣", type: "武器", desc: "魔宝。" }),

  // ==================== 典籍 / 材料 -> 杂项 ====================
  createItem({ id: "zx_001", name: "天南手札", price: 1200, width: 1, height: 2, quality: "黄", type: "杂项", desc: "记录了越国及邻近地区的风土人情和奇闻异事。" }),
  createItem({ id: "zx_002", name: "五行初级咒决大全", price: 600, width: 1, height: 2, quality: "黄", type: "杂项", desc: "提供修仙者入门级的法术教育。" }),
  createItem({ id: "zx_003", name: "水咒符法基础", price: 620, width: 1, height: 2, quality: "黄", type: "杂项", desc: "提供入门级水系咒法与符法基础。" }),
  createItem({ id: "zx_004", name: "基础咒决残本", price: 180, width: 1, height: 1, quality: "凡", type: "杂项", desc: "修仙入门残本。" }),
  createItem({ id: "zx_005", name: "青溪笔录", price: 1200, width: 1, height: 2, quality: "黄", type: "杂项", desc: "保存了青溪真人关于越国秘史的珍贵记述。" }),
  createItem({ id: "zx_006", name: "兽皮书", price: 4600, width: 2, height: 2, quality: "玄", type: "杂项", desc: "藏有疾风九变、血影遁、匿风术等秘术。" }),
  createItem({ id: "zx_007", name: "云霄心得", price: 5200, width: 2, height: 2, quality: "玄", type: "杂项", desc: "齐云霄对炼器艺术的深刻见解。" }),
  createItem({ id: "zx_008", name: "万灵真经", price: 16000, width: 2, height: 3, quality: "地", type: "杂项", desc: "揭示鬼灵门修行法门的典籍。" }),
  createItem({ id: "zx_009", name: "傀儡真经", price: 22000, width: 2, height: 3, quality: "地", type: "杂项", desc: "揭示傀儡操控之术的核心典籍。" }),
  createItem({ id: "zx_010", name: "洞玄解", price: 3600, width: 2, height: 2, quality: "玄", type: "杂项", desc: "黄枫谷的内部典籍。" }),
  createItem({ id: "zx_011", name: "弄焰决", price: 4200, width: 2, height: 2, quality: "玄", type: "杂项", desc: "吴仙师的独创控火技艺。" }),
  createItem({ id: "zx_012", name: "丹道评鉴", price: 2600, width: 2, height: 2, quality: "玄", type: "杂项", desc: "详述了乱星海丹药的分类与效果。" }),
  createItem({ id: "zx_013", name: "天地奇石录", price: 3200, width: 2, height: 2, quality: "玄", type: "杂项", desc: "收录了稀世材料的详尽说明。" }),
  createItem({ id: "zx_014", name: "法阵要诀", price: 12000, width: 2, height: 3, quality: "地", type: "杂项", desc: "凝聚了辛如音对法阵构造的理解。" }),
  createItem({ id: "zx_015", name: "天鹏之誓", price: 36000, width: 3, height: 3, quality: "地", type: "杂项", desc: "承载着天鹏族的古老誓言与力量。" }),
  createItem({ id: "zx_016", name: "朱砂", price: 40, width: 1, height: 1, quality: "凡", type: "杂项", desc: "炼制低阶符箓的材料。" }),
  createItem({ id: "zx_017", name: "铁精", price: 2200, width: 1, height: 2, quality: "玄", type: "杂项", desc: "法宝原料。" }),
  createItem({ id: "zx_018", name: "铜精", price: 2000, width: 1, height: 2, quality: "玄", type: "杂项", desc: "法宝原料。" }),
  createItem({ id: "zx_019", name: "银精", price: 6000, width: 1, height: 2, quality: "地", type: "杂项", desc: "法宝原料。" }),
  createItem({ id: "zx_020", name: "坞石", price: 180, width: 1, height: 1, quality: "凡", type: "杂项", desc: "耐高温材料。" }),
  createItem({ id: "zx_021", name: "云精石", price: 800, width: 1, height: 1, quality: "黄", type: "杂项", desc: "炼制二级傀儡的材料。" }),
  createItem({ id: "zx_022", name: "铁木", price: 1800, width: 2, height: 2, quality: "玄", type: "杂项", desc: "制作傀儡的材料之一。" }),
  createItem({ id: "zx_023", name: "炼晶", price: 16000, width: 2, height: 2, quality: "地", type: "杂项", desc: "用于加固法宝。" }),
  createItem({ id: "zx_024", name: "幻梦石", price: 2600, width: 1, height: 2, quality: "玄", type: "杂项", desc: "用于传送阵的材料。" }),
  createItem({ id: "zx_025", name: "玛瑙角", price: 3200, width: 1, height: 2, quality: "玄", type: "杂项", desc: "炼丹的珍惜材料。" }),
  createItem({ id: "zx_026", name: "千叶露", price: 3000, width: 1, height: 2, quality: "玄", type: "杂项", desc: "伴妖草的汁液。" }),
  createItem({ id: "zx_027", name: "魄石", price: 6800, width: 1, height: 2, quality: "地", type: "杂项", desc: "用于傀儡术和鬼道修士修炼。" }),
  createItem({ id: "zx_028", name: "青金石", price: 12000, width: 2, height: 2, quality: "地", type: "杂项", desc: "又叫吸灵石。" }),
  createItem({ id: "zx_029", name: "醇液", price: 18000, width: 1, height: 2, quality: "地", type: "杂项", desc: "灵眼之树流出的灵液，可配明清灵水。" }),
  createItem({ id: "zx_030", name: "庚精", price: 46000, width: 2, height: 2, quality: "天", type: "杂项", desc: "锐金之宝，可使法宝威力倍增。" }),
  createItem({ id: "zx_031", name: "血凤木", price: 18000, width: 2, height: 3, quality: "地", type: "杂项", desc: "炼制上古元婴级傀儡的材料。" }),
  createItem({ id: "zx_032", name: "罡银沙", price: 16000, width: 2, height: 2, quality: "地", type: "杂项", desc: "可使法宝更加坚固。" }),
  createItem({ id: "zx_033", name: "魔髓钻", price: 36000, width: 2, height: 2, quality: "天", type: "杂项", desc: "炼制魔龙刃的唯一材料。" }),
  createItem({ id: "zx_034", name: "火熔晶", price: 14000, width: 2, height: 2, quality: "地", type: "杂项", desc: "炼制顶阶火属性法器的绝佳材料。" }),
  createItem({ id: "zx_035", name: "寒髓", price: 32000, width: 2, height: 2, quality: "天", type: "杂项", desc: "炼制回阳真水的主原料。" }),
  createItem({ id: "zx_036", name: "玉橡胶", price: 16000, width: 2, height: 2, quality: "地", type: "杂项", desc: "制作奇门法宝、机关傀儡的最佳材料。" }),
  createItem({ id: "zx_037", name: "五行玉", price: 18000, width: 2, height: 2, quality: "地", type: "杂项", desc: "炼制玉质法宝的顶阶材料。" }),
  createItem({ id: "zx_038", name: "化神泥", price: 42000, width: 2, height: 3, quality: "天", type: "杂项", desc: "又称幻形膏，可随意变形炼制成器。" }),
  createItem({ id: "zx_039", name: "灵料", price: 62000, width: 3, height: 3, quality: "天", type: "杂项", desc: "炼制通天灵宝的材料。" }),
  createItem({ id: "zx_040", name: "传界香", price: 18000, width: 1, height: 2, quality: "地", type: "杂项", desc: "点燃此香可隔界传递消息。" }),
  createItem({ id: "zx_041", name: "蜃楼石", price: 18000, width: 2, height: 2, quality: "地", type: "杂项", desc: "小极宫护岛大阵的阵眼。" }),
  createItem({ id: "zx_042", name: "阴灵水", price: 12000, width: 1, height: 2, quality: "地", type: "杂项", desc: "又叫沉水，可让法器临时附加阴火。" }),
  createItem({ id: "zx_043", name: "万年玄玉", price: 26000, width: 2, height: 2, quality: "地", type: "杂项", desc: "可产生寒髓。" }),
  createItem({ id: "zx_044", name: "蓝元晶", price: 18000, width: 2, height: 2, quality: "地", type: "杂项", desc: "炼制飞剑的材料。" }),
  createItem({ id: "zx_045", name: "天晶碑", price: 32000, width: 2, height: 3, quality: "天", type: "杂项", desc: "又叫飞仙石，用于加固昆吾封印。" }),
  createItem({ id: "zx_046", name: "太阳精石", price: 36000, width: 2, height: 2, quality: "天", type: "杂项", desc: "只有经过太阳精火凝炼才可形成。" }),
  createItem({ id: "zx_047", name: "顶阶灵石", price: 52000, width: 2, height: 2, quality: "天", type: "杂项", desc: "布置上古奇阵和突破瓶颈的必须之物。" }),
  createItem({ id: "zx_048", name: "化界石", price: 78000, width: 3, height: 3, quality: "圣", type: "杂项", desc: "灵界也难得一见的材料，可克服界面之力。" }),
  createItem({ id: "zx_049", name: "神血", price: 86000, width: 2, height: 2, quality: "圣", type: "杂项", desc: "灵族圣灵级存在死后体内所留。" }),
];
